--- # Config file for Unreal Launcher
unreal:
	start_game: true
	use_docker: false
	headless: true
	engine_path: "/home/mindful/EpicGames/UE5.1"
	project_path: "/home/mindful/Documents/UnrealProjects/MountainVillageEnvironmen"
	actors_to_tag: "OrangeBall:TrackMe,Cone:TrackMe"

simulation:
	num_lives: 6
	time: 120
	tags_to_track: "TrackMe"
